project:
  type: website
  output-dir: "_site"
  resources:
    - .nojekyll
    - CNAME
    - "/res/*"
    - "/libs/*"
    - "/content/**/*.pdf"
  render:
    - "*.qmd"
    - "!TODO.md"
    - "!LICENSE.md"
    - "!src/"
    - "!res/"
    - "!libs/"

website:
  title: "Agalic Rodriguez-Duboc"
  description: "MD & PhD in Developmental Neuroscience ◈ Passionate about Science, Arts, and Books"
  image: res/avatar.jpg
  favicon: res/favicon.png
  site-url: 'https://agalic-rd.com'
  
  ### Analytics ###
  google-analytics:
    tracking-id: "G-J4N8PQ8FCW"
  cookie-consent:
    type: implied
  
  ### Sharing ###
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@Agalic21"
    card-style: summary
  
  ### Search ###
  search:
    location: navbar
    type: overlay
    collapse-after: 10
  
  ### Navigation ###
  # page-navigation: true
  navbar:
    # logo: TODO
    # logo-alt: ""
    pinned: true
    collapse: true
    collapse-below: md
    left:
      - text: "{{< fa business-time >}} Projects"
        file: content/projects/index.qmd
        aria-label: "A list of the projects I was or am involved in"
      - text: "{{< fa book >}} Publications"
        file: content/pubs/index.qmd
        aria-label: "A list of my scientific writings"
      - text: "{{< iconify file-icons keynote height=20px >}} Communications"
        file: content/sci-com/index.qmd
        aria-label: "A list of my Posters & Talks"
      - text: "{{< fa palette >}} Art"
        file: content/sci-art/index.qmd
        aria-label: "A sample of my artistic production"
      - text: "Code"
        icon: code-slash
        file: content/code/index.qmd
        aria-label: "A list of my R and stats projects"
    right:
      - text: "{{< fa user-tie >}} About Me"
        file: content/about.qmd
        aria-label: "About Me"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/agalic-rd/agalic-rd.com
            aria-label: "Website's source code"
  
  ### Sidebar ###
  sidebar: false
  
  ### Footer ###
  page-footer:
    border: true
    left: 
      - text: "© 2022-2023, Agalic Rodriguez-Duboc"
        href: LICENSE.md
        aria-label: "Website's license"
    right:
      - text: "Made with Quarto ♥️"
        href: https://quarto.org/
        aria-label: "Quarto's website"


from: markdown+emoji
bibliography: res/refs.bib
csl: res/apa.csl
link-citations: true

citation: false
comments: false
toc: false

format:
  html:
    theme: [default, libs/css/light.scss]
    css: libs/css/style.css
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
    df-print: paged
    fig-align: center
    fig-dpi: 500
    fig-format: svg
    # fig-cap-location: bottom
    anchor-sections: true
    footnotes-hover: true
    code-link: true
    code-copy: hover
    code-block-bg: true
    code-overflow: scroll
    highlight-style: libs/highlight-styles/light.theme
    link-external-newwindow: true

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

editor: source